###  Directories to find data ###
DATA_DIR_OUTPUT = "../data/processed/"
DATA_FILE = 'reduced_data.csv'
DATA_DIR = "../data/raw/"

FACTORS = { "In": [
        "loanId",
        "interest_rate",        
        "balance",
        "current_interest_rate",
        "originalLoanAmt",
        "loan_term",
        "origination_date",
        'acquisition_date',
        "ltv",
        "cltv",
        "borrowers_count",
        "dti",
        "borrower_credit_score",
        "first_time_homebuyer",
        "property_state",
        "zip",
        "insurance_percentage",
        "co_borrower_credit_score"
],
  }

fields = {
    "LoanData" : [
    "loanId", 
    "reporting_period",
    "channel",
    "seller",
    "interest_rate",
    "current_interest_rate",
    "originalLoanAmt",
    "loan_term",
    "origination_date",
    "balance",
    "loan_age",
    "maturity_date",    
    "ltv",
    "cltv",
    "borrowers_count",
    "dti",
    "borrower_credit_score",
    "co-borrower_credit_score",
    "first_time_homebuyer",
    "loan_purpose",
    "property_type",
    "units_num",
    "property_state",
    "zip",
    "recovery_costs",
    "borrower_credit_score_current",
    "co-borrower_credit_score_current", 
    "insurance_type",
    "foreclosure_date",
    "relocation_indicator",
    "insurance_percentage",
    "high_balance_loan_ind"
   ]
}
Original_Headers = {
    "LoanData" : [
    "ReferencePoolID",
    "loanId",
    "reporting_period",
    "channel",
    "seller",
    "servicer_name",
    "master_servicer",
    "interest_rate",
    "current_interest_rate",
    "originalLoanAmt",
    "UPB at Issuance",
    "balance",
    "loan_term",
    "origination_date",
    "first_payment_date",
    "loan_age",
    "Remaining Months to Legal Maturity",
    "Remaining Months To Maturity",
    "maturity_date",
    "ltv",
    "cltv",
    "borrowers_count",
    "dti",
    "borrower_credit_score",
    "co-borrower_credit_score",
    "first_time_homebuyer",
    "loan_purpose",
    "property_type",
    "units_num",
    "occupancy_status",
    "property_state",
    "Metropolitan Statistical Area (MSA)",
    "zip",
    "insurance_percentage",
    "Amortization Type",
    "Prepayment Penalty Indicator",
    "Interest Only Loan Indicator",
    "Interest Only First Principal And Interest Payment Date",
    "Months to Amortization",
    "Current Loan Delinquency Status",
    "Loan Payment History",
    "Modification Flag",
    "Mortgage Insurance Cancellation Indicator",
    "Zero Balance Code",
    "Zero Balance Effective Date",
    "UPB at the Time of Removal",
    "Repurchase Date",
    "Scheduled Principal Current",
    "Total Principal Current",
    "Unscheduled Principal Current",
    "Last Paid Installment Date",
    "foreclosure_date",
    "Disposition Date",
    "Foreclosure Costs",
    "Property Preservation and Repair Costs",
    "recovery_costs",
    "Miscellaneous Holding Expenses and Credits",
    "Associated Taxes for Holding Property",
    "Net Sales Proceeds",
    "Credit Enhancement Proceeds",
    "Repurchase Make Whole Proceeds",
    "Other Foreclosure Proceeds",
    "Modification-Related Non-Interest Bearing UPB",
    "Principal Forgiveness Amount",
    "Original List Start Date",
    "Original List Price",
    "Current List Start Date",
    "Current List Price",
    "Borrower Credit Score At Issuance",
    "Co-borrower Credit Score At Issuance",
    "borrower_credit_score_current",
    "co-borrower_credit_score_current",
    "insurance_type",
    "Servicing Activity Indicator",
    "Current Period Modification Loss Amount",
    "Cumulative Modification Loss Amount",
    "Current Period Credit Event Net Gain or Loss",
    "Cumulative Credit Event Net Gain or Loss",
    "Special Eligibility Program",
    "Foreclosure Principal Write-off Amount",
    "relocation_indicator",
    "Zero Balance Code Change Date",
    "Loan Holdback Indicator",
    "Loan Holdback Effective Date",
    "Delinquent Accrued Interest",
    "Property Valuation Method",
    "high_balance_loan_ind",
    "ARM Initial Fixed-Rate Period  ≤ 5 YR Indicator",
    "ARM Product Type",
    "Initial Fixed-Rate Period",
    "Interest Rate Adjustment Frequency",
    "Next Interest Rate Adjustment Date",
    "Next Payment Change Date",
    "Index",
    "ARM Cap Structure",
    "Initial Interest Rate Cap Up Percent",
    "Periodic Interest Rate Cap Up Percent",
    "Lifetime Interest Rate Cap Up Percent",
    "Mortgage Margin",
    "ARM Balloon Indicator",
    "ARM Plan Number",
    "Borrower Assistance Plan",
    "High Loan to Value (HLTV) Refinance Option Indicator",
    "Deal Name",
    "Repurchase Make Whole Proceeds Flag",
    "Alternative Delinquency Resolution",
    "Alternative Delinquency  Resolution Count",
    "Total Deferral Amount"    ]
  }


STATES_TO_VAL = { 
    'AL' : 1,
    'AK' : 2,
    'AS' : 3,
    'AZ' : 4,
    'AR' : 5,
    'CA' : 6,
    'CO' : 7,
    'CT' : 8,
    'DE' : 9,
    'DC' : 10,
    'FL' : 11,
    'GA' : 12,
    'GU' : 13,
    'HI' : 14,
    'ID' : 15,
    'IL' : 16,
    'IN' : 17,
    'IA' : 18,
    'KS' : 19,
    'KY' : 20,
    'LA' : 21,
    'ME' : 22,
    'MD' : 23,
    'MA' : 24,
    'MI' : 25,
    'MN' : 26,
    'MS' : 27,
    'MO' : 28,
    'MT' : 29,
    'NE' : 30,
    'NV' : 31,
    'NH' : 32,
    'NJ' : 33,
    'NM' : 34,
    'NY' : 35,
    'NC' : 36,
    'ND' : 37,
    'MP' : 38,
    'OH' : 39,
    'OK' : 40,
    'OR' : 41,
    'PA' : 42,
    'PR' : 43,
    'RI' : 44,
    'SC' : 45,
    'SD' : 46,
    'TN' : 47,
    'TX' : 48,
    'UT' : 49,
    'VT' : 50,
    'VA' : 51,
    'VI' : 52,
    'WA' : 53,
    'WV' : 54,
    'WI' : 55,
    'WY' : 56
}

